# Generated by Django 2.1.2 on 2018-10-08 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("url", models.URLField()),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("number", models.IntegerField(default=1)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("highest", "Highest"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("lowest", "Lowest"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                (
                    "gifter",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("wishlist", "id")},
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=128)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("shared", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="wishlist",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="lists.Wishlist"),
        ),
        migrations.AlterUniqueTogether(name="wishlist", unique_together={("owner", "title")}),
        migrations.AlterUniqueTogether(name="item", unique_together={("text", "wishlist")}),
    ]
