# Generated by Django 2.1.2 on 2018-10-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
