# Generated by Django 2.1.1 on 2018-09-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.Wishlist'),
        ),
    ]
