# Generated by Django 2.1.1 on 2018-09-10 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_item_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f5d3a506-86c9-4e61-91a3-0d3ea0cae080'), editable=False),
        ),
    ]
