# Generated by Django 2.1.1 on 2018-09-10 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180910_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0228f62e-19f3-40f8-ab2e-b641fc250186'), editable=False, unique=True),
        ),
    ]
