# Generated by Django 2.2.6 on 2019-10-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lists", "0007_wishlist_archived")]

    operations = [
        migrations.AddField(
            model_name="item", name="archived", field=models.BooleanField(default=False)
        )
    ]
