# Generated by Django 3.1.2 on 2020-10-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_auto_20201004_1701'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='Unique wishlist items',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('text', 'wishlist', 'uuid'), name='Unique wishlist items'),
        ),
    ]
