# Generated by Django 3.1.2 on 2020-10-05 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_auto_20201005_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
