# Generated by Django 3.1.2 on 2020-10-05 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0015_item_quantity_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_bought',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]))]),
        ),
    ]
