# Generated by Django 3.1.2 on 2020-10-08 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0017_auto_20201007_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifter',
            name='gifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
