# Generated by Django 3.1.2 on 2020-10-08 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0018_auto_20201008_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gifters',
            field=models.ManyToManyField(default=None, null=True, related_name='item_gifters', through='lists.Gifter', to=settings.AUTH_USER_MODEL),
        ),
    ]
