# Generated by Django 3.1.2 on 2020-10-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0020_auto_20201008_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity_bought',
        ),
    ]
